# Ekstraksi Fitur tf idf Berita

In [1]:
import pandas as pd

# Load data from pta_manajemen.csv
df = pd.read_csv('hasil_preprocessing_berita.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'hasil_preprocessing_berita.csv'

In [2]:
# Display basic information about the dataset
print("Dataset shape:", df.shape)
df

Dataset shape: (1432, 3)

,isi,hasil_preprocessing,kategori
0,KOMPAS.com -Pengalaman tak menyenangkan kabarn...,"['kompascom', 'alam', 'senang', 'kabar', 'alam...",Bola
1,"JAKARTA, KOMPAS.com –Tiktokers Figha Lesmana m...","['jakarta', 'kompascom', 'tiktokers', 'figha',...",Megapolitan
2,KOMPAS.com -Wakil Presiden Direktur PT Toyota ...,"['kompascom', 'wakil', 'presiden', 'direktur',...",Money
3,"JAKARTA, KOMPAS.com- Menteri Koordinator Bidan...","['jakarta', 'kompascom', 'menteri', 'koordinat...",Nasional
4,"JAKARTA, KOMPAS.com- Menteri Pertanian (Mentan...","['jakarta', 'kompascom', 'menteri', 'tani', 't...",Nasional
...,...,...,...
1427,"JAKARTA, KOMPAS.com- Sosok pengacara Farhat Ab...","['jakarta', 'kompascom', 'sosok', 'acara', 'fa...",Entertainment
1428,"JAKARTA, KOMPAS.com- Memasuki musim hujan, per...","['jakarta', 'kompascom', 'pasuk', 'musim', 'hu...",Otomotif
1429,"KOMPAS.com- Ramadan 2025 baru saja dimulai, da...","['kompascom', 'ramadan', 'samsung', 'langsung'...",Tekno
1430,"JAKARTA, KOMPAS.com- Program pemutihan pajak k...","['jakarta', 'kompascom', 'program', 'mutih', '...",Otomotif
1431,"JAKARTA, KOMPAS.com- Kapolri Jenderal Pol List...","['jakarta', 'kompascom', 'kapolri', 'jenderal'...",Otomotif

##  Ekstraksi Fitur TF-IDF

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
# Kolom teks hasil preprocessing
texts = df["hasil_preprocessing"].astype(str)

# Kalau ada kolom label
labels = df["kategori"]

##  TF-IDF Vectorization

In [5]:
vectorizer = TfidfVectorizer()

# Fit & transform ke matriks TF-IDF
tfidf_matrix = vectorizer.fit_transform(texts)

# Konversi ke DataFrame agar lebih mudah dibaca
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Tambahkan kolom label
tfidf_df["kategori"] = labels.values

In [6]:
print("Ukuran matriks TF-IDF:", tfidf_df.shape)
tfidf_df

Ukuran matriks TF-IDF: (1432, 21370)

,aa,aaib,aal,aam,aau,ab,abaaax,abad,abadi,abai,...,zuefeng,zul,zulhas,zulhasmi,zulhelmi,zulkifli,zulpata,zurich,zvulunperdana,zwiers
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1428,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.203004,0.0,0.0,0.0
1429,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1430,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1431,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

In [7]:
output_file = "hasil_tfidf_berita.csv"

# index=False biar tidak ikut nyimpan index dataframe
tfidf_df.to_csv(output_file, index=False, encoding="utf-8")

print(f"Hasil TF-IDF berhasil disimpan ke file: {output_file}")

Hasil TF-IDF berhasil disimpan ke file: hasil_tfidf_berita.csv